# Generated by Django 5.0.7 on 2024-07-31 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_aboutme_img_aboutme_imgs_alter_aboutme_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
