# Generated by Django 5.0.7 on 2024-07-31 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_publication_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(default=True, max_length=120),
        ),
    ]
